# What's a data view? {#whats-a-data-view}

The term 'view' is used throughout subsequent sections of this book, so here we take a moment to frame its use in a wider context. This term is often used in interactive statistical graphics literature, and @Wills2008 puts it quite nicely, "a 'data view' can be though of as anything that gives the user a way of examining data so as to gain insight and understanding. A data view is usually thought of as a barchart, scatterplot, or other traditional statistical graphic, but we use the term more generally, including 'views' such as the results of a regression analysis, a neural net prediction, or a set of descriptive statistics".

In this book, more often than not, the term 'view' typically refers to a statistical graphic. In fact, Section \@ref(graphical-queries) is all about linking multiple graphics together through a graphical database querying framework. However, many of the concepts covered can be applied more generally to any 'view', especially Section \@ref(linking-server-side) since the reactive programming framework that **shiny** provides is agnostic towards the type of view that one is linking.